=begin
	
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	
=end



def fib(last_number)
	four_mil = 4000000
	numbers = [1,1]

	numbers.push(1)
	sum_numbers = 1

	while numbers[-1] < four_mil

		numbers.push(numbers[-2] + numbers[-1])
		sum_numbers += numbers[-1]
	end

	# Removes 2 first items
	numbers.shift
	numbers.shift

	puts "#{numbers}"

	sum_numbers = 0
	numbers.each {|i| 
		if i % 2 == 0 and i < four_mil
			sum_numbers += i
		else
			# nothing
		end
	}

	puts sum_numbers

end

fib(5)

puts "end"
# ex = [1,2,3,4]
# puts ex[-1]
# puts ex[-2]